=== flancer64/dBEAR/dBEAR.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.flancer64.com/dBEAR/Schema"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://www.flancer64.com/dBEAR/Schema">

	<complexType name="BaseType">
		<all>
			<element name="entities" type="tns:ArrayEntitiesType"
				minOccurs="1" maxOccurs="1">
			</element>
		</all>
		<attribute name="version" type="int" use="required">
			<annotation>
				<documentation>Ordinal number of the version of the data
					structure.
				</documentation>
			</annotation>
		</attribute>
	</complexType>

	<complexType name="EntityType">
		<all>
			<element name="notes" type="string" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>
						Human related description of the entity.
					</documentation>
				</annotation>
			</element>
			<element name="attributes" type="tns:ArrayAttributesType"
				minOccurs="1" maxOccurs="1">
			</element>
		</all>
		<attribute name="alias" use="required" type="tns:AliasType">
			<annotation>
				<documentation>Alias to be used in the tables and views names.
				</documentation>
			</annotation>
		</attribute>
	</complexType>

	<complexType name="AttributeType">
		<all>
			<element name="name" type="tns:NameType" minOccurs="1"
				maxOccurs="1">
				<annotation>
					<documentation>This value is used to name columns in views.
					</documentation>
				</annotation>
			</element>
			<element name="notes" type="string">
				<annotation>
					<documentation>
						Human related description of the entity.
					</documentation>
				</annotation>
			</element>
			<element name="type" type="string" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>SQL data type to store attribute values.
					</documentation>
				</annotation>
			</element>
		</all>
		<attribute name="alias" use="required" type="tns:AliasType">

			<annotation>
				<documentation>
					Alias to be used in the tables and views names.
				</documentation>
			</annotation>
		</attribute>
		<attribute name="temporal" use="required" type="boolean">
			<annotation>
				<documentation>Is this attribute temporal (need save all updates)?
				</documentation>
			</annotation>
		</attribute>
		<attribute name="required" type="boolean" use="required">
			<annotation>
				<documentation>Is this attribute should contain value for all
					instances of the entity (is not nullable)?
				</documentation>
			</annotation>
		</attribute>
	</complexType>

	<complexType name="RelationType"></complexType>

	<element name="dBEAR" type="tns:BaseType"></element>

	<complexType name="ArrayAttributesType">
		<sequence>
			<element name="attribute" type="tns:AttributeType" minOccurs="1"
				maxOccurs="unbounded"></element>
		</sequence>
	</complexType>
	<complexType name="ArrayEntitiesType">
		<sequence>
			<element name="entity" type="tns:EntityType" minOccurs="1"
				maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<simpleType name="AliasType">
		<annotation>
			<documentation>Alias for entities, attributes, etc. Used in the
				naming rules for tables and views.
			</documentation>
		</annotation>
		<restriction base="string">
			<minLength value="1"></minLength>
			<maxLength value="8"></maxLength>
			<whiteSpace value="collapse"></whiteSpace>
		</restriction>
	</simpleType>

	<simpleType name="NameType">
		<annotation>
			<documentation>Alias for entities, attributes, etc. Used in the
				naming rules for tables and views.
			</documentation>
		</annotation>
		<restriction base="string">
			<minLength value="1"></minLength>
			<maxLength value="64"></maxLength>
			<whiteSpace value="collapse"></whiteSpace>
		</restriction>
	</simpleType>

</schema>

=== flancer64/dBEAR/php/test/etc/xml/schema.v3.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:dBEAR xmlns:tns="http://www.flancer64.com/dBEAR/Schema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.flancer64.com/dBEAR/Schema ../etc/dBEAR.xsd " version="3">
    <tns:entities>
        <tns:entity alias="cust">
            <tns:notes>Customer</tns:notes>
            <tns:attributes>
                <tns:attribute alias="nfirst" temporal="false" required="true">
                    <tns:type>String</tns:type>
                    <tns:name>NameFirst</tns:name>
                    <tns:notes>Customer's first name.</tns:notes>
                </tns:attribute>
                <tns:attribute alias="nlast" temporal="false" required="true">
                    <tns:type>String</tns:type>
                    <tns:name>NameLast</tns:name>
                    <tns:notes>Customer's Last Name.</tns:notes>
                </tns:attribute>
                <tns:attribute alias="email" temporal="false" required="true">
                    <tns:type>String</tns:type>
                    <tns:name>Email</tns:name>
                    <tns:notes>Customer's email.</tns:notes>
                </tns:attribute>
            </tns:attributes>
        </tns:entity>
        <tns:entity alias="addr">
            <tns:notes>Address</tns:notes>
            <tns:attributes>
                <tns:attribute alias="zip" temporal="false" required="false">
                    <tns:type>String</tns:type>
                    <tns:name>Zip</tns:name>
                    <tns:notes>ZIP code or postal code.</tns:notes>
                </tns:attribute>
                <tns:attribute alias="country" temporal="false" required="false">
                    <tns:type>String</tns:type>
                    <tns:name>CountryCode</tns:name>
                    <tns:notes>2 letters code of the country.</tns:notes>
                </tns:attribute>
            </tns:attributes>
        </tns:entity>
    </tns:entities>
</tns:dBEAR>

=== flancer64/dBEAR/php/etc/dBEAR.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:dBEAR xmlns:tns="http://www.flancer64.com/dBEAR/Schema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.flancer64.com/dBEAR/Schema ../etc/dBEAR.xsd " version="2">
    <tns:entities>
        <tns:entity alias="cust">
            <tns:notes>Customer notes</tns:notes>
            <tns:attributes>
                <tns:attribute alias="nfirst" temporal="false" required="true">
                    <tns:type>String</tns:type>
                    <tns:name>NameFirst</tns:name>
                    <tns:notes>Customer's first name.</tns:notes>
                </tns:attribute>
                <tns:attribute alias="nlast" temporal="false" required="true">
                    <tns:type>String</tns:type>
                    <tns:name>NameLast</tns:name>
                    <tns:notes>Customer's Last Name.</tns:notes>
                </tns:attribute>
                <tns:attribute alias="phone" temporal="false" required="true">
                    <tns:type>String</tns:type>
                    <tns:name>Phone</tns:name>
                    <tns:notes>Customer's phone.</tns:notes>
                </tns:attribute>
                <tns:attribute alias="height" temporal="false" required="true">
                    <tns:type>String</tns:type>
                    <tns:name>Height</tns:name>
                    <tns:notes>Рост.</tns:notes>
                </tns:attribute>
                <tns:attribute alias="class" temporal="false" required="true">
                    <tns:type>String</tns:type>
                    <tns:name>Class</tns:name>
                    <tns:notes>Класс.</tns:notes>
                </tns:attribute>
            </tns:attributes>
        </tns:entity>
    </tns:entities>
</tns:dBEAR>

=== flancer64/dBEAR/php/etc/dBEAR.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:dBEAR xmlns:tns="http://www.flancer64.com/dBEAR/Schema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.flancer64.com/dBEAR/Schema ../etc/dBEAR.xsd " version="10">
    <tns:entities>
        <tns:entity alias="cust">
            <tns:notes>Customer notes</tns:notes>
            <tns:attributes>
                <tns:attribute alias="nfirst" temporal="false" required="true">
                    <tns:type>String</tns:type>
                    <tns:name>NameFirst</tns:name>
                    <tns:notes>Customer's first name.</tns:notes>
                </tns:attribute>
                <tns:attribute alias="nlast" temporal="false" required="true">
                    <tns:type>String</tns:type>
                    <tns:name>NameLast</tns:name>
                    <tns:notes>Customer's Last Name.</tns:notes>
                </tns:attribute>
                <tns:attribute alias="email" temporal="true" required="true">
                    <tns:type>String</tns:type>
                    <tns:name>Email</tns:name>
                    <tns:notes>Customer's email.</tns:notes>
                </tns:attribute>
            </tns:attributes>
        </tns:entity>
    </tns:entities>
</tns:dBEAR>
